In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
iris = pd.read_csv("iris.csv")

In [3]:
iris.isnull().values.any()

False

In [4]:
iris.sample(5)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
5      6            5.4           3.9            1.7           0.4   
27    28            5.2           3.5            1.5           0.2   
60    61            5.0           2.0            3.5           1.0   
140  141            6.7           3.1            5.6           2.4   
13    14            4.3           3.0            1.1           0.1   

             Species  
5        Iris-setosa  
27       Iris-setosa  
60   Iris-versicolor  
140   Iris-virginica  
13       Iris-setosa

In [5]:
x = iris.iloc[:,1:4]
x

SepalLengthCm  SepalWidthCm  PetalLengthCm
0              5.1           3.5            1.4
1              4.9           3.0            1.4
2              4.7           3.2            1.3
3              4.6           3.1            1.5
4              5.0           3.6            1.4
..             ...           ...            ...
145            6.7           3.0            5.2
146            6.3           2.5            5.0
147            6.5           3.0            5.2
148            6.2           3.4            5.4
149            5.9           3.0            5.1

[150 rows x 3 columns]

In [6]:
y = iris.iloc[:,4:5]
y

PetalWidthCm
0             0.2
1             0.2
2             0.2
3             0.2
4             0.2
..            ...
145           2.3
146           1.9
147           2.0
148           2.3
149           1.8

[150 rows x 1 columns]

In [7]:
x = iris.iloc[:,1:4].values
y = iris.iloc[:,4:5].values

In [8]:
print(y.shape)

(150, 1)


In [9]:
print(x.shape)

(150, 3)


In [10]:
x = (x - x.mean()) / x.std()
x

array([[ 0.53412873, -0.43554521, -1.70824225],
       [ 0.41291949, -0.73856832, -1.70824225],
       [ 0.29171024, -0.61735907, -1.76884687],
       [ 0.23110562, -0.67796369, -1.64763763],
       [ 0.47352411, -0.37494059, -1.70824225],
       [ 0.71594259, -0.19312673, -1.52642839],
       [ 0.23110562, -0.49614983, -1.70824225],
       [ 0.47352411, -0.49614983, -1.64763763],
       [ 0.10989638, -0.79917294, -1.70824225],
       [ 0.41291949, -0.67796369, -1.64763763],
       [ 0.71594259, -0.31433597, -1.64763763],
       [ 0.35231486, -0.49614983, -1.58703301],
       [ 0.35231486, -0.73856832, -1.70824225],
       [ 0.04929176, -0.73856832, -1.89005612],
       [ 0.95836108, -0.1325221 , -1.8294515 ],
       [ 0.89775645,  0.10989638, -1.64763763],
       [ 0.71594259, -0.19312673, -1.76884687],
       [ 0.53412873, -0.43554521, -1.70824225],
       [ 0.89775645, -0.25373135, -1.52642839],
       [ 0.53412873, -0.25373135, -1.64763763],
       [ 0.71594259, -0.49614983, -1.526

In [11]:
print(x.shape)

(150, 3)


In [12]:
x.shape[0]

150

In [13]:
a = np.array([1,2,3])
b = np.array([10,20,30])
print(np.dot(a,b))
# 10 + 40 + 90

# 1x3, 1x3 - np.dot(): not runnig like matrix multiplication
# there is a different function for this: np.matmul()
# so if we calculate np.dot of 2 vectors having not matching dimensions then it not returns vector,, it returns scaler.""

140


In [14]:
a = np.array([1])      # it must be a sclaer, not even 1-D vector
b = np.array([10,20,30])
print(np.dot(a,b))

ValueError: shapes (1,) and (3,) not aligned: 1 (dim 0) != 3 (dim 0)

In [15]:
a = np.array(1)      # it must be a sclaer, not even 1-D vector
b = np.array([10,20,30])
print(np.dot(a,b))

[10 20 30]


In [16]:
# for only one sample

def Multivariate_Gradient_Descent(x, y, w, b, alpha, iters):
    
    for iter in range(iters):
        n = len(x)                                          # number of features - here: 3
        m = 1

        dj_dw = np.zeros(n)                                 # [0 0 0]
        dj_db = 0                                           # scaler

        y_pred = np.dot(x, w) + b                           # 1-D vector: [x1 x2 x3][w1 w2 w3] this dot product returns scaler

        for j in range(n):
            dj_dw[j] = (y_pred - y)*x[j]
        
        dj_db = (y_pred - y)

        dj_dw = dj_dw/m                                     # 1x3 vector
        dj_db = dj_db/m                                     # scaler 

        w = w - alpha*dj_dw                                 # 1x3 vector: [w1 w2 w3] - [dw1 dw2 dw3]
        b = b - alpha*dj_db                                 # scaler - scaler
    
    return w, b

In [17]:
print(x[0])
print(y[0])
print(x.shape)

[ 0.53412873 -0.43554521 -1.70824225]
[0.2]
(150, 3)


In [18]:
w = np.zeros(x.shape[1])
print(w.shape)

(3,)


In [19]:
alpha = 0.01

w = np.zeros(x.shape[1]) # w:[0, 0, 0]
b = 0

iters = 1000

# for only one sample
w, b =  Multivariate_Gradient_Descent(x[0], y[0], w, b, alpha, iters)


In [20]:
print(f"Final w:{w} and Final b:{b}")

Final w:[ 0.0243168  -0.01982867 -0.0777696 ] and Final b:[0.0455261]


In [21]:
np.sum([1,2,3])

6

# 5 Gradient Descent With Multiple Variables
Gradient descent for multiple variables:

$$\begin{align*} \text{repeat}&\text{ until convergence:} \; \lbrace \newline\;
& w_j = w_j -  \alpha \frac{\partial J(\mathbf{w},b)}{\partial w_j} \tag{5}  \; & \text{for j = 0..n-1}\newline
&b\ \ = b -  \alpha \frac{\partial J(\mathbf{w},b)}{\partial b}  \newline \rbrace
\end{align*}$$

where, n is the number of features, parameters $w_j$,  $b$, are updated simultaneously and where  

$$
\begin{align}
\frac{\partial J(\mathbf{w},b)}{\partial w_j}  &= \frac{1}{m} \sum\limits_{i = 0}^{m-1} (f_{\mathbf{w},b}(\mathbf{x}^{(i)}) - y^{(i)})x_{j}^{(i)} \tag{6}  \\
\frac{\partial J(\mathbf{w},b)}{\partial b}  &= \frac{1}{m} \sum\limits_{i = 0}^{m-1} (f_{\mathbf{w},b}(\mathbf{x}^{(i)}) - y^{(i)}) \tag{7}
\end{align}
$$
* m is the number of training examples in the data set

    
*  $f_{\mathbf{w},b}(\mathbf{x}^{(i)})$ is the model's prediction, while $y^{(i)}$ is the target value


In [22]:
def Multivariate_Gradient_Descent(x, y, w, b, alpha, iters):
    
    for iter in range(iters):
    
        m = x.shape[0] # number of samples
        n = x.shape[1] # number of features
        
        dj_dw = np.zeros(n,)
        dj_db = 0

        for i in range(m):
            y_pred = (np.dot(x[i],w) + b) - y[i]
            
            for j in range(n):
                dj_dw[j] = dj_dw[j] + (y_pred)*x[i][j]
            
            dj_db = dj_db + y_pred
        
        dj_dw = dj_dw/m
        dj_db = dj_db/m

        w = w - alpha*dj_dw                        
        b = b - alpha*dj_db                        
    
    return w, b

In [23]:
a = np.array([[1,2],
              [3,4]])      
b = np.array([10,20])
print(np.dot(a,b))

# [1,2] [10,20]
# [3,4]

[ 50 110]


In [24]:
alpha = 0.01
iters = 1000

x = iris.iloc[:,1:4].values

w = np.zeros(x.shape[1])
b = 0

w, b =  Multivariate_Gradient_Descent(x, y, w, b, alpha, iters)

In [25]:
print(f"Final w:{w} and Final b:{b}")

Final w:[-0.08757498  0.02326325  0.45017579] and Final b:[-0.05039142]


# We can draw a plane in n-D which is best fit to our datapoints.
## where n = number of features