In [1]:
import numpy as np



In [2]:

def convolve(image, kernel):
    m, n = kernel.shape
    y, x = image.shape
    y = y - m + 1
    x = x - n + 1
    new_image = np.zeros((y, x))
    for i in range(y):
        for j in range(x):
            new_image[i][j] = np.sum(image[i:i+m, j:j+n]*kernel)
    return new_image


def relu(x):
    return np.maximum(x, 0)


vertical_edge_filter = np.array([[-1, 0, 1],
                                 [-1, 0, 1],
                                 [-1, 0, 1]])


def cnn(image):
    image = np.pad(image, ((1, 1), (1, 1)), mode='constant')
    conv = convolve(image, vertical_edge_filter)
    output = relu(conv)
    return output




In [3]:
image = np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10],
                  [11, 12, 13, 14, 15],
                  [16, 17, 18, 19, 20],
                  [21, 22, 23, 24, 25]])
output = cnn(image)
print(output)

[[ 9.  4.  4.  4.  0.]
 [21.  6.  6.  6.  0.]
 [36.  6.  6.  6.  0.]
 [51.  6.  6.  6.  0.]
 [39.  4.  4.  4.  0.]]
